apiVersion: skaffold/v2alpha4
kind: Config

metadata:
  name: popular-slides

build:
  artifacts:

    - image: schaeufler/impfpass-frontend
      context: impfpass-frontend

    - image: schaeufler/impfpass-vaccination-microservice
      context: impfpass-vaccination-microservice

    - image: schaeufler/impfpass-user-microservice
      context: impfpass-user-microservice

    - image: schaeufler/impfpass-vaccination-streaming
      context: impfpass-vaccination-streaming

deploy:
  kubectl:
    manifests:
      - k8s/*.yaml
