#Ingress for frontend and backend
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: impfpass-ingress
#have a look at https://kubernetes.io/docs/concepts/services-networking/ingress/
spec:
  tls:
    - hosts:
        - vac.book
      secretName: imfpass-tls-secret
  rules:
    - host: vac.book
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: impfpass-frontend-service
                port:
                  number: 3000
          - path: /vaccinationapi
            pathType: Prefix
            backend:
              service:
                name: impfpass-vaccination-service
                port:
                  number: 3000
          - path: /userapi
            pathType: Prefix
            backend:
              service:
                name: impfpass-user-service
                port:
                  number: 3000